# Подбайте, щоб `node` був доступний у вашому середовищі розробки
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported

# Підготовка проекту React Native для подальшої інтеграції
prepare_react_native_project!

# Налаштування використання бібліотек з можливістю посилання через frameworks або статично
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Основна цільова група
target 'MyFabricApp' do
  # Використання нативних модулів, налаштованих у проекті
  config = use_native_modules!

  # Використання React Native з налаштуванням шляху до кореня програми
  use_react_native!(
    :path => config[:reactNativePath],
    # Абсолютний шлях до кореня вашої програми
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Цільова група для тестування
  target 'MyFabricAppTests' do
    inherit! :complete
    # Місце для підключення тестових бібліотек
    # Наприклад, додайте бібліотеки для тестування тут
    # pod 'something_for_tests'
  end

  # Пост-інсталяційний скрипт для налаштування React Native
  post_install do |installer|
    # Запуск пост-інсталяційних дій для React Native, включаючи налаштування Fabric
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true # Якщо ви хочете використовувати ccache
    )

    # Додаткові налаштування для підтримки нової архітектури
    installer.pods_project.targets.each do |target|
      if target.name == "React-Core"
        target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
      end

      # Додаткові налаштування, якщо використовуються TurboModules або інші нативні компоненти
      if target.name == "YogaKit"
        target.build_configurations.each do |config|
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
      end
    end
  end
end
