package Podfile

platform :ios, '10.0'

target 'YourApp' do
  use_frameworks!

  pod 'Flipper', '~> 0.54.0'
  pod 'Flipper-Folly', '~> 2.3'
  pod 'Flipper-RSocket', '~> 1.0'
  pod 'Flipper-Boost', '~> 1.76.0'
  pod 'Flipper-React', '~> 0.54.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end